### ISSUE TITLE
set repository topics

### ISSUE THREAD

**Issue by kevinpapst** [mxgross/EasyBackupBundle#1]
my first wish: add some topics to your repo, so its easier to find

example screenshot [from the CustomCSSBundle](https://github.com/Keleo/CustomCSSBundle):

<img width="769" alt="Bildschirmfoto 2019-12-18 um 18 20 23" src="https://user-images.githubusercontent.com/533162/71108285-11d91480-21c3-11ea-96a2-57a27869f469.png">

**Comment by mxgross** [comment]
Thanks, I added some :)
