### ISSUE TITLE
add gitignore to var/easy_backup

### ISSUE THREAD

**Issue by kevinpapst** [mxgross/EasyBackupBundle#10]
Currently `git status` will report var/easy_backup and all backups as unknown/new files.

This could be fixed by creating a `.gitignore` file with the contents:
```
*
```
when creating the `var/easy_backup/` directory.

**Comment by mxgross** [comment]
Good idea. I implemented it in commit 2b8128e.
Now that I found out, I can link the commits by using  '#<issue number>' in the commit message,I will use this feature from now on. :)
