### ISSUE TITLE
Idea: Include the directories templates and invoice

### ISSUE THREAD

**Issue by roerigdalgaard** [mxgross/EasyBackupBundle#13]
After fix #11 :-) and Idea.

Can you include the
templates/
var/invoice/

dirs in the backup. Thats where the maintaint documents relies :-)

/Martin
PS: excelent fast work with isuue #11 :-) !!

**Comment by mxgross** [comment]
Thanks for your feedback to #11 :)
Good idea to include these directories. I will definitely implement this :)

**Comment by roerigdalgaard** [comment]
Appreciated :-)
Maybe to consideration:
- add cron ability 
- add uploads to OneDrive/DropBox/Gdrive :-)

**Comment by mxgross** [comment]
Feel free to create descriptive issues for these, and future feature requests :)     Am Mittwoch, 8. Januar 2020, 10:28:19 MEZ hat roerigdalgaard <notifications@github.com> Folgendes geschrieben:  
 
 
Appreciated :-)
Maybe to consideration:
   
   - add cron ability
   - add uploads to OneDrive/DropBox/Gdrive :-)
