### ISSUE TITLE
add your invoices directory to backup

### ISSUE THREAD

**Issue by aptevo** [mxgross/EasyBackupBundle#18]
Add your invoices directory to $arrayOfPathsToBackup in Controller/EasyBackupController.php to have them backed up automatically.

**Comment by mxgross** [comment]
Which path did you mean exactly, the template/invoice path is already added in the latest version:
[https://github.com/mxgross/EasyBackupBundle/blob/d6a61132f31eb1e914f02b576c8505bf5aa3b161/Controller/EasyBackupController.php#L148](https://github.com/mxgross/EasyBackupBundle/blob/d6a61132f31eb1e914f02b576c8505bf5aa3b161/Controller/EasyBackupController.php#L148)

**Comment by kevinpapst** [comment]
Maybe `var/invoices/` - see 
https://www.kimai.org/documentation/invoices.html#create-your-own-invoice-document

You could even use the `%kimai.invoice.documents%` parameter and inject all configured search paths for invoice templates.

**Comment by mxgross** [comment]
I added the path but I will leave this issue open and implement the usage of the %kimai.invoice.documents% parameter soon.
