### ISSUE TITLE
Error bin/console cache:clear

### ISSUE THREAD

**Issue by markus7777777** [mxgross/EasyBackupBundle#19]
I followed the instructions of  EasyBackupBundle, but an error occurs after executing the command "cache:clear".

Steps:

cd /var/www/kimai2/var/plugins/
git clone https://github.com/mxgross/EasyBackupBundle.git

cd var/www/kimai2/
bin/console cache:clear

**Error Message:**

_In FileLoader.php line 208:

  Expected to find class "KimaiPlugin\EasyBackupBundle\Controller\EasyBackupController" in file "/var/www/kimai2/var/plugins/E
  asyBackupBundle/Controller/EasyBackupController.php" while importing services from resource "../../*", but it was not found!
   Check the namespace prefix used with the resource.

Used software:
_Kimai version: 1.8;
Ubuntu Desktop 
nginx 
php 7.2_

**Comment by mxgross** [comment]
Can you please try to update the permissions once again 
```
chown -R :www-data .
chmod -R g+r .
chmod -R g+rw var/
chmod -R g+rw public/avatars/
```
and then again 
```
cd var/www/kimai2/
bin/console cache:clear
```

**Comment by markus7777777** [comment]
Hi,
I have made some changes since the issue I created. I made an update to kimai 1.9 and php runs on 7.3 like you do.

It now works fine with your description. I don't know if it is because of the permissions after the git clone or because of the php and kimai version. I think it was to adjust the file permissions directly after the git clone.

Thanks for your answer. It's running now :)

**Comment by yweidmann** [comment]
Hi
I encoutered the same problem (see email correspondance).

According to the messages, I checked the ownership of the plugin-directory ./kimai2/var/plugins/EasyBackupBoundle: It is not owned by the group and user www-data.

Could that be the reason?

**Comment by mxgross** [comment]
Hello Yvo,
yes that seems to be the reason. In markus case it helped to follow my steps described in my first comment in this issue here.
Afterwards the permissions should be fixed.

**Comment by yweidmann** [comment]
Mh, we tried again calling _bin/console cache:clear_ with sudo as user. But we got the following error-messages:

```
PHP Fatal error:  Class 'App\Plugin\AbstractPluginExtension' not found in /home/yweidmann/subdomains/projects/kimai2/var/plugins/EasyBackupBundle/DependencyInjection/EasyBackupExtension.php on line 18

In EasyBackupExtension.php line 18:

  Attempted to load class "AbstractPluginExtension" from namespace "App\Plugin".
  Did you forget a "use" statement for another namespace?

cache:clear [--no-warmup] [--no-optional-warmers] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command>
```

Any ideas?
