### ISSUE TITLE
Error creating backup

### ISSUE THREAD

**Issue by MAPIIIAJI** [mxgross/EasyBackupBundle#23]
When creating backup, I get the following error:
![Screenshot_20200709_122328](https://user-images.githubusercontent.com/35526267/87009874-39371380-c1df-11ea-8d8b-0534d24f5ef4.png)
P.S. Kimai deploy in docker
![image](https://user-images.githubusercontent.com/35526267/87010116-887d4400-c1df-11ea-87d0-492a16bd96a3.png)

Respectfully,
Jamshid Tursunov

**Comment by mxgross** [comment]
Hallo Jamshid,
I have no docker setup but it seems like your path to the mysqldump command is wrong.
Maybe try to login to the docker with a terminal and type `which mysqldump` to see where it is located. Then you can change the path in the kimai settings page like described in my documentation.

Best regards,
Max
