### ISSUE TITLE
Add Restore Capabilities

### ISSUE THREAD

**Issue by marcseguin** [mxgross/EasyBackupBundle#24]
Thanks for the Plug-In! 
Nevertheless backups have no sense if the restore of them is not rock solid. It would be great to have some restore capabilities or at least a guidance how to restore what is in the backup.

**Comment by mxgross** [comment]
Hello,
as long as there is no restore functionality, use this instruction: https://www.kimai.org/documentation/backups.html
In the chapter "restore" is everything descriped.

**Comment by mxgross** [comment]
Currently I am working on the restore functionality. I hope I can provide it soon.

**Comment by mxgross** [comment]
Hello @marcseguin 
would you like to test the restore functionality of the [pull request](https://github.com/mxgross/EasyBackupBundle/pull/32)?
Therefor you can checkout the 'dev' branch.
