### ISSUE TITLE
Add capabilities to backup invoice templates and other customized objects

### ISSUE THREAD

**Issue by marcseguin** [mxgross/EasyBackupBundle#25]
Some effort is also in invoice templates and customized objects. It will be nice to get them backed up too.

**Comment by mxgross** [comment]
Which directory do you mean exactly? Currently the following directories and files are backuped:

.env
config/packages/local.yaml
var/data/
var/plugins/
templates/invoice

Maybe it woeuld be a good idea to let the user define which files and paths sould be backuped.

**Comment by mxgross** [comment]
Hello @marcseguin,
I just made an update of the plugin with the possibility to edit the backuped paths and files at the kimai settings page. 
For testing the feature you could switch to the dev branch of this repository. I would be happy to receive feedback from you.
I will test it in another productive environment soon, but yet it is only tested in an development environment on my windows machine with XAMPP as webserver.

Thanks,
Max

**Comment by marcseguin** [comment]
Hi, thx a lot. I hope I will find the time to follow your proposal for testing. Currently I'm working to get our (user)-test and production environment up and running. For setting up a separate dev environment I need to find the time :-/
