### ISSUE TITLE
Files and paths to backup settings: only last path taken into account

### ISSUE THREAD

**Issue by biologghe** [mxgross/EasyBackupBundle#33]
In my hands (Firefox Browser on Windows 10 Enterprise and Kimai 1.12 stable running on Pi) the paths entered in the settings 'Files and paths to backup) are not all taken into account. Only when content of the form field is deleted and saved (= defaults are taken) all files and folders are taken into account. As the default values are filled in automatically, you need to remember to delete the content every time you make changes to other settings.
Looks like a PHP_EOL issue (https://eidson.info/post/php_eol_is_broken)

**Comment by biologghe** [comment]
Should have checked dev branch. Fixed already ...

**Comment by mxgross** [comment]
Hi,
thanks for looking at the dev branch. I would really appreciate if you would like to test the new restore functionality. 
I did not merge it to the master yet because I only tested it in my environments.

Best regards,
Max

**Comment by biologghe** [comment]
Hi Max,
What is the best/easiest channel to communicate with? (this is reply to
email notification).

FYI I did a restore attempt but bumped into this error:
[2020-12-27 15:48:00] request.CRITICAL: Uncaught PHP Exception
Symfony\Component\Filesystem\Exception\IOException: "Cannot rename
"/home/pi/kimai2/var/easy_backup/2020-12-27_151908/.env" to
"/home/pi/kimai2/.env"." at
/home/pi/kimai2/vendor/symfony/filesystem/Filesystem.php line 290
{"exception":"[object]
(Symfony\\Component\\Filesystem\\Exception\\IOException(code: 0): Cannot
rename \"/home/pi/kimai2/var/easy_backup/2020-12-27_151908/.env\" to
\"/home/pi/kimai2/.env\". at
/home/pi/kimai2/vendor/symfony/filesystem/Filesystem.php:290)"} []

I had changed the permissions of .env to g+rw

HTH,
Marc
