### ISSUE TITLE
Default backuped directories are not saved anymore after changing path to mysqldump

### ISSUE THREAD

**Issue by jaysalty** [mxgross/EasyBackupBundle#36]
As I use a Synology NAS for Kimai the path to mysqldump is:
_/volume1/@appstore/MariaDB10/usr/local/mariadb10/bin/mysqldump_

instead of the default setting:
_/usr/bin/mysqldump_

When I changed the path in EasyBackup configurations (Kimai UI) I finally was able to backup the mysql database.
The files and paths to backup didnt change, so the following files/folders should be backed up too:

- .env
- config/packages/local.yaml
- var/data/
- var/plugins/
- var/invoices/
- templates/invoice/
- var/export/
- templates/export/

Unfortunately now the created zip-file does only contain following files:

- templates (folder with subfolders)
- database_dump.sql 
- manifest.json

Why cant I backup all the necessary files anymore?
Kimai is a great Software, but it would be useless for me, if i cant backup my files reliably.
Can anybody help me?

**Comment by mxgross** [comment]
Hi, I think I already have fixed this issue in m development branch. I just merged in the master branch. Please execute a „git pull“ or update your sources of the plugin to the latest version.

Then go to the Kimai EasyBackup Settings and correct and save them again. Then create a backup and check it.

If something seems wrong/missing then please check the „Latest log“ in the EasyBackup main page.
If there are further problems please report them here and upload your log.

Thanks,
Max

**Comment by jaysalty** [comment]
Now everything is working fine...you made my day! Thx a lot!
