### ISSUE TITLE
unable to change bin path on an Synology NAS

### ISSUE THREAD

**Issue by GoProAndy** [mxgross/EasyBackupBundle#37]
Hi,

i host my kimai on an synology NAS. There are the paths different to an usual linux server.
My Synology has it installed here:
/volume1/@appstore/MariaDB10/usr/local/mariadb10/bin

Can you please add an possibility to change the path to the bins or check it via the server variables?

thanks
Andreas

<img width="1213" alt="Screenshot 2021-02-15 at 20 39 03" src="https://user-images.githubusercontent.com/8830326/107987621-a2310600-6fce-11eb-90c0-6b870c6cad7e.png">

**Comment by mxgross** [comment]
Hi,
you can configure the path at the kimai settings page.
![90DBD696-F263-4F85-831D-4842B9E3ED55](https://user-images.githubusercontent.com/3718449/107989690-11105e00-6fd3-11eb-93dc-bd815c2e3883.jpeg)

Kind regards,
Max
