### ISSUE TITLE
Password from DATABASE_URL needs urldecode to convert %

### ISSUE THREAD

**Issue by keestux** [mxgross/EasyBackupBundle#44]
Hello,

The password from `DATABASE_URL` can contain `%40` to allow a `@` character in the password. This works well in Kimai, but not in EasyBackup.

How about replacing this
```
            $mysqlDumpCmd = str_replace('{password}', $dbPwd, $mysqlDumpCmd);
```
by
```
            $mysqlDumpCmd = str_replace('{password}', urldecode($dbPwd), $mysqlDumpCmd);
```

**Comment by mxgross** [comment]
Hi,
good idea, I commited it like you suggested. 
Thanks
