### ISSUE TITLE
Create Backup fails

### ISSUE THREAD

**Issue by YulianaPoliakova** [mxgross/EasyBackupBundle#45]
View status checks have every entry in the list displaced as correct. However, when tried to create a backup this page with a critical error pops up. The backup is attempted to be done through the super admin account

![image](https://user-images.githubusercontent.com/65809471/187892159-56467554-efba-4537-813b-9f82e221c55a.png)

**Comment by numerfolt** [comment]
I had the exact same problem. I am on version 1.20.4.
In the logfile it says:
`[2022-09-14 14:39:16] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Filesystem\Exception\IOException: "Failed to touch "/var/www/kimai2/var/easy_backup/easybackup.log"." at /var/www/kimai2/vendor/symfony/filesystem/Filesystem.php line 151 {"exception":"[object] (Symfony\\Component\\Filesystem\\Exception\\IOException(code: 0): Failed to touch \"/var/www/kimai2/var/easy_backup/easybackup.log\". at /var/www/kimai2/vendor/symfony/filesystem/Filesystem.php:151)"} []`

I manually created the folder /var/www/kimai2/var/easy_backup/ and it worked right away. 
Not sure though why my php user couldnt create it as the permissions were correctly set (using the manual of this repository).

**Comment by mxgross** [comment]
Thanks I created a new wiki page with [Common-errors-and-their-solution](https://github.com/mxgross/EasyBackupBundle/wiki/Common-errors-and-their-solution)
I hope I'll soon find time to further optimize the problematic parts of the code.
