### ISSUE TITLE
SQL parameters seemingly not found

### ISSUE THREAD

**Issue by noseshimself** [mxgross/EasyBackupBundle#48]
Current version of plugin and Kimai2.

The plugin was pulled from git without any modifications or configuration:

![image](https://user-images.githubusercontent.com/6132793/193594720-db2f2097-ac04-47ed-829b-2d0ddeeb4b34.png)

Running it results in

```
[2022-10-03 13:20:52] INFO: Start database backup.
[2022-10-03 13:20:52] INFO: Used database: 'mysql'.
[2022-10-03 13:20:52] ERROR: Usage: mysqldump [OPTIONS] database [tables]
OR     mysqldump [OPTIONS] --databases DB1 [DB2 DB3...]
OR     mysqldump [OPTIONS] --all-databases
OR     mysqldump [OPTIONS] --system=[SYSTEMOPTIONS]]
For more options, use mysqldump --help
[2022-10-03 13:20:52] INFO: Start zipping '/opt/kimai/var/easy_backup/2022-10-03_132052/' to '/opt/kimai/var/easy_backup/2022-10-03_132052.zip'.
```

so it looks like the correct parameters are not found in the Kimai configuration...

**Comment by noseshimself** [comment]
I did some debugging...

My database configuration doesn't contain a port number (as the database is running on the default port). Your script should check for empty parameters as this resulted in a "--port= "...

**Comment by mxgross** [comment]
Thanks for your feedback. I will implement a solution that respects the default port / no port and escapes the password.

**Comment by mxgross** [comment]
I updated my implementation using parse_url. I tested it with your URL which leads to 
```
array(5) {
  ["scheme"]=>
  string(5) "mysql"
  ["host"]=>
  string(10) "db-bnc-net"
  ["user"]=>
  string(5) "kimai"
  ["pass"]=>
  string(23) "$882934$6166472$1151515"
  ["path"]=>
  string(6) "/kimai"
}
```
I trim all slashes (/) from the path and I remove the whole `--port={port}` part when no "port" key exits.
This should solve your problem. Please give me feedback about it.

**Comment by noseshimself** [comment]
Thanks. 1) Working as expected now. Sorry for my late answer but I was so concentrated on not getting Covid that the flu (which is just as deadly) caught up with me.

Regarding 2) I can use any password I want so I can obviously create one without any $ sign but you might warn users that the shell may and will interact with the command line it will receive from you.
