### ISSUE TITLE
NOT --version sh: 1: NOT: not found 

### ISSUE THREAD

**Issue by wforumw** [mxgross/EasyBackupBundle#49]
Hi,
I have installed easybackup as described [here](https://www.kimai.org/store/maximiliangross-easy-backup-bundle.html)
In the 'View status checks' overview I get this error 

```
Path '/var/www/kimai2/var' readable 	
Path '/var/www/kimai2/var' writable 	
Backup directory '/var/www/kimai2/NOT SET' exists 	
PHP extension 'zip' loaded 	
Kimai version 	1.26.0 stable
Database 	mysql
NOT --version 	sh: 1: NOT: not found
NOT --version 	sh: 1: NOT: not found 
```

Any idea why?

**Comment by mxgross** [comment]
Hi,

please try recreating the cache and report me if the problem still exists

Inside the /kimai/ directory execute
```
bin/console cache:clear
bin/console cache:warmup
```
Sometimes the permissions must be set again

```
sudo chown -R :www-data .
sudo chmod -R g+r .
sudo chmod -R g+rw var/
sudo chmod -R g+rw public/avatars/
```
It looks like the configuration could not be read.
Maybe also check the Kimai Settings page. At the bottom you will find the EasyBackup settings. Please check if there are valid values existing e.g. for the mysqldump command.

**Comment by mxgross** [comment]
Otherwise please try replacing the EasyBackupExtension.php with the following file included in the zip.
[EasyBackupExtension.zip](https://github.com/mxgross/EasyBackupBundle/files/9754412/EasyBackupExtension.zip)
Maybe I have to convert it back to that.
Please tell me if it works.
Thanks

**Comment by mxgross** [comment]
Can you add the code
` $this->log(self::LOG_INFO_PREFIX, $mysqlDumpCmd);`
in this line here https://github.com/mxgross/EasyBackupBundle/blob/master/Controller/EasyBackupController.php#L532

And then check the log please so we see what command is tried to use. Please remove the passwort part from the output before you post it here.

Also you can delete the directory "NOT SET" which was created by accident.
Thanks.

**Comment by mxgross** [comment]
Okay thanks. There should be a default entry available already.
 I changed something with the config and it seem like it is not working in fresh installations / when EasyBackup was never installed before. 
I will try to test it and fix it. Thanks for your feedback.
