### ISSUE TITLE
Easy Backup not working in Docker

### ISSUE THREAD

**Issue by aogmike** [mxgross/EasyBackupBundle#50]
Hello, is it possible to run this plugin in docker?
I am getting the following errors:
sh: /usr/bin/mysqldump: not found
sh: /usr/bin/mysql: not found

**Comment by mxgross** [comment]
Hi @aogmike,

yes you can also use it in docker. But therefor you must setup your docker container according to it.
So you must include mysqldump in your docker setup file.

I am not a docker expert but here seems to be some other Github project which already implements a docker with kimai2 and some plugins, inlcuding EasyBackup: [mplx/docker-kimai](https://github.com/mplx/docker-kimai) from @mplx

In his file "Dockerfile" you can see what is included into the docker.
But the kimai version is hardcoded to KIMAI="1.6.2", so you might want to change some settings in this Dockerfile before you build your individual one suitable for you.
