### ISSUE TITLE
Problem with special characters in DB password?

### ISSUE THREAD

**Issue by webaff** [mxgross/EasyBackupBundle#61]
Hi,

I get the following error when creating a backup:
`ERROR: sh: -c: line 0: syntax error near unexpected token `('`

I suspect this to happen due to the "(" character in the database password.
Can anyone confirm/fix this?

Thx

**Comment by mxgross** [comment]
Hi @webaff ,
can you please pull the main branch and try it again.

I wrapped the password with an escapeshellarg command and hope it will help.
In my case everythin works like before, but I did not yet test it with a mysql password containing a "(".

**Comment by webaff** [comment]
Hi @mxgross , it's working with "(" in the password now! Great job, thanks.
