### ISSUE TITLE
Detected "dubious ownership" message

### ISSUE THREAD

**Issue by Rudiberto** [mxgross/EasyBackupBundle#64]
EasyBackup seems to work, but showing this message:
```
git 	fatal: detected dubious ownership in repository at '/var/www/kimai/var/plugins/EasyBackupBundle' To add an exception for this directory, call: git config --global --add safe.directory /var/www/kimai/var/plugins/EasyBackupBundle 
```
![grafik](https://github.com/mxgross/EasyBackupBundle/assets/96433043/8768da45-24d9-42ac-82f8-6c52b044700d)

I've tried the recommendation written there, but it doesn't solve the issue. So what ownership is working for the directory? What is the reason for the error message, since I followed the instructions step by step?

I'm posting here based on Kevin's recommendation. 
I'm on the last release, 2.14.0 as you see in the screenshot.

**Comment by mxgross** [comment]
Duplicate issue.  but anyway:
Please try to find a suitable solution for your system. A starting point could be be [here](https://stackoverflow.com/questions/72978485/git-submodule-update-failed-with-fatal-detected-dubious-ownership-in-reposit).

This git message does not affect functionality in any way and can therefore be ignored.
Git seems to throw it if a repository is contained inside a repository.

**Comment by Rudiberto** [comment]
`git config --system --add safe.directory /var/www/kimai/var/plugins/EasyBackupBundle `
This solved the problem for me. Used _--system_ instead of _--global_.
**Sorry** for the duplicated issue.

**Comment by mxgross** [comment]
Thanks for posting your solution, I think I will add this to my Readme.md.
