### ISSUE TITLE
Error: Using a password on the command line interface can be insecure. 

### ISSUE THREAD

**Issue by Jakob-Moe** [mxgross/EasyBackupBundle#65]
The backups are created in the folder but not shown in the plugin Gui.
Is there any workaround?

<img width="382" alt="image" src="https://github.com/user-attachments/assets/bf020ff2-38d6-4ced-bd8f-f8b1257ced9b">
<img width="1212" alt="image" src="https://github.com/user-attachments/assets/2c8e9f56-2d58-4590-8c54-1898d15d233b">

**Comment by mxgross** [comment]
It's a warning from mysql during the execution of the mysqldump command which backups the database.
You could try to change the settings of the EasyBackup plugin in kimai to use 
`mysqldump --defaults-extra-file=/path/to/config.cnf `
and then put the credentials inside your config.cnf
```
[client]
user = "yourUsername"
password = "yourSecret"
host = "yourHost"
```

If this doesn't work, you may find other solutions here: [](https://stackoverflow.com/questions/20751352/suppress-warning-messages-using-mysql-from-within-terminal-but-password-written)

**Comment by Jakob-Moe** [comment]
Thanks for the Help. Works fine!
