### ISSUE TITLE
Make flash messages translatable

### ISSUE THREAD

**Issue by mxgross** [mxgross/EasyBackupBundle#8]
Currently the flash messages are hardcoded in english. They should be made translatable and be available at least in english and german.

**Comment by kevinpapst** [comment]
Use `addFlashTranslated()` instead of `addFlash()`.
Then you have to use `flashmessages.de.xlf` for translation.

**Comment by mxgross** [comment]
Thanks. I implemented it for de and en

**Comment by kevinpapst** [comment]
Ups forgot: you could even use `flashSuccess()`, `flashWarning()` and `flashError()` to get rid of your own constants and to be safe for coming updates.
